# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d1f307dac579d7234ca364c2c4e54729661064201d084d1060434f1b880dad1c20101d82f118471a85c1fbf2c7e6669961695eff5bf7195a18f60785748c963

test:
  secret_key_base: 23d7ab61752356e32bcc2cefd3c14465af859faddbcdd13a353ad88dd7e8ad3e49f9646f29876871307eb3e8e5c31ceed16a2c87779aef93be09533f1ef3866b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
